version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: Laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend
  db:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: tinyuser
      POSTGRES_DB: laravel
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    networks:
      - backend
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - backend
networks:
  backend:
    driver: bridge